### ISSUE TITLE
Register Overflow with deviceaccess.Device.write()

### ISSUE THREAD

**Issue by Amadrath** [ChimeraTK/DeviceAccess-PythonBindings#48]
It is possible to unintentionally write data from RAM to a register, using deviceaccess.Device.write(). This occurs, if a list, which is to be written to a register, is shorter than that register. In that case all registers after the last element in the list is written with whatever is in the memory.

Example:
```
>>> import deviceaccess as da
>>> da.setDMapFilePath('devices.dmap')
>>> dev = da.Device('APP')
>>> dev.open()
>>> print(dev.read('BSP.FCM')[0:120])
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>>> dev.write('BSP.FCM', [1, 2, 3, 4, 5, 6], 10)
>>> print(dev.read('BSP.FCM')[0:120])
[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.   2.   3.   4.
   5.   6. 255.  65.   1.   2.   3.   4.   5.   6. 255. 161. 255. 255.
 144.   0. 240.  12. 255.  65.  16.   1.  46.  32. 255.  56.  12. 255.
  65.  88.   1.  46. 144. 255.   0.   8.   2.   0.   0.   0. 112. 132.
 132. 255. 255.  10.  32.  32.  16.  32.   0.  33.  48.  48.   0.   0.
  48.  11. 255.  84.  80.   1. 255. 255. 255. 120.  11. 255. 255. 152.
   1. 255. 255. 255.   0.  56.   0.   0.   0.   0. 224. 244. 244. 255.
 255.  10.  96.  32. 144.  32.   0.  33.  96.  48. 192. 144. 112.  11.
 255. 255. 144.   1.  46.  65. 255. 184.]
```

**Comment by Amadrath** [comment]
The reason for this is, that length of the vector, to be written to the register, is derived from the length of the register itself, instead of the length of the input:
```python
    def write(self, registerPath: str,
              dataToWrite: registerInputTypes,
              wordOffsetInRegister: int = 0,
              accessModeFlags: Sequence[AccessMode] = None) -> None:
        catalogue = self.getRegisterCatalogue()
        register = catalogue.getRegister(registerPath)
        # This defines the length of the written data, instead of the length of the given input data!
        number_of_elements = register.getNumberOfElements() - wordOffsetInRegister
        # make proper array, if number was submitted
        if isinstance(dataToWrite, list):
            array = np.array(dataToWrite)
            # upgrade 1d-list input two the 2d that is expected for scalar and 1d lists:
            if not array.ndim == 2:
                array = np.array([dataToWrite])
        elif not isinstance(dataToWrite, np.ndarray):
            array = np.array([[dataToWrite]])
        else:
            array = dataToWrite

        accessModeFlags = [] if accessModeFlags is None else accessModeFlags
        self._device.write(array, registerPath, number_of_elements, wordOffsetInRegister, accessModeFlags)

``` 
Is there a specific reason, why it is implemented in this way? As tests with _device.write() suggest, that smaller vectors would then write only parts of the register, as would be expected.

**Comment by Amadrath** [comment]
This issue is now fixed:

```
>>> import deviceaccess as da
>>> import numpy as np
>>> da.setDMapFilePath('devices.dmap')
>>> dev = da.Device('APP')
>>> dev.open()
>>> print(dev.read('FCM.AREA_WRITE')[0:120])
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]
>>> dev.write('FCM.AREA_WRITE', [1, 2, 3, 4, 5, 6], 10)
>>> print(dev.read('FCM.AREA_WRITE')[0:120])
[0 0 0 0 0 0 0 0 0 0 1 2 3 4 5 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]
>>> dev.write('FCM.AREA_WRITE', [0] * 6, 10)
>>> print(dev.read('FCM.AREA_WRITE')[0:120])
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]
```
Note: I also tested, if it is possible to write into a neighboring register by using an overlong array:
```
>>> dev.write('FCM.AREA_WRITE', [5, 8, 3], 1022)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/deviceaccess.py", line 1428, in write
    self._device.write(array, registerPath, numberOfElements,
RuntimeError: Requested number of words exceeds the size of the register '/FCM.AREA_WRITE'!
>>> print(dev.read('FCM.AREA_WRITE')[1020:])
[0 0 0 0]
>>> print(dev.read('FCM.AREA_READ')[:4])
[0 0 0 0]
```
As shown above, it is not. A RuntimeError exception is thrown and the registers are not written.
